# Generated by Django 3.2.21 on 2023-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
