# Generated by Django 3.2.21 on 2023-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_book_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='code',
            field=models.UUIDField(blank=True, null=True, verbose_name='uuid'),
        ),
    ]
